/* $Id: interp.h,v 1.125 2004/04/25 00:32:05 boogums Exp $" */
/* this is a listing of all the commands and command related data */

/* for command types */
#define ML  MAX_LEVEL /* implementor */
#define L1  MAX_LEVEL - 1   /* creator */
#define L2  MAX_LEVEL - 2 /* supreme being */
#define L3  MAX_LEVEL - 3 /* deity */
#define L4  MAX_LEVEL - 4 /* god */
#define L5  MAX_LEVEL - 5 /* immortal */
#define L6  MAX_LEVEL - 6 /* demigod */
#define L7  MAX_LEVEL - 7 /* angel */
#define L8  MAX_LEVEL - 8 /* avatar */
#define IM  LEVEL_IMMORTAL  /* angel */
#define HE  LEVEL_HERO  /* hero */

#define COM_INGORE  1

/*
 * Structure for a command in the command lookup table.
 */
struct  cmd_type
{
    char * const  name;
    DO_FUN *    do_fun;
    sh_int    position;
    sh_int    level;
    sh_int    log;
    sh_int    show;
    sh_int    order;
};

/* the command table itself */
extern  const struct  cmd_type  cmd_table [];
extern  int     nAllocString;
extern  int     nAllocPerm;

/*
 * Command functions.
 * Defined in act_*.c (mostly).
 */
DECLARE_DO_FUN( do_abolish      );
DECLARE_DO_FUN( do_advance  );
DECLARE_DO_FUN( do_affects  );
DECLARE_DO_FUN( do_afk    );
DECLARE_DO_FUN( do_alia   );
DECLARE_DO_FUN( do_alias  );
DECLARE_DO_FUN( do_allow  );
DECLARE_DO_FUN( do_ally  );
DECLARE_DO_FUN( do_answer );
DECLARE_DO_FUN( do_areas  );
DECLARE_DO_FUN( do_at   );
DECLARE_DO_FUN( do_assemble );
DECLARE_DO_FUN( do_attack );
DECLARE_DO_FUN( do_attributes );
DECLARE_DO_FUN( do_auction  );
DECLARE_DO_FUN( do_autoassist );
DECLARE_DO_FUN( do_autoexit );
DECLARE_DO_FUN( do_autogold );
DECLARE_DO_FUN( do_autolist );
DECLARE_DO_FUN( do_autoloot );
DECLARE_DO_FUN( do_autopeek );
DECLARE_DO_FUN( do_autosac  );
DECLARE_DO_FUN( do_autosplit  );
DECLARE_DO_FUN( do_backstab );
DECLARE_DO_FUN( do_bamfin );
DECLARE_DO_FUN( do_bamfout  );
DECLARE_DO_FUN( do_ban    );
DECLARE_DO_FUN( do_bash   );
DECLARE_DO_FUN( do_beeptell );
DECLARE_DO_FUN( do_berserk  );
DECLARE_DO_FUN( do_bite  );
DECLARE_DO_FUN( do_dbite );
DECLARE_DO_FUN( do_bladesong );
DECLARE_DO_FUN( do_bleed  );
DECLARE_DO_FUN( do_bflag  );
DECLARE_DO_FUN( do_brandish );
DECLARE_DO_FUN( do_breathe  );
DECLARE_DO_FUN( do_brew );
DECLARE_DO_FUN( do_brief  );
DECLARE_DO_FUN( do_bug    );
DECLARE_DO_FUN( do_bump   );
DECLARE_DO_FUN( do_buy    );
DECLARE_DO_FUN( do_callies  );
DECLARE_DO_FUN( do_cast   );
DECLARE_DO_FUN( do_changepassword  );
DECLARE_DO_FUN( do_changes  );
DECLARE_DO_FUN( do_channels );
DECLARE_DO_FUN( do_chant        );
DECLARE_DO_FUN( do_chelp        );
DECLARE_DO_FUN( do_cinfo  );
DECLARE_DO_FUN( do_clist  );
DECLARE_DO_FUN( do_clone  );
DECLARE_DO_FUN( do_close  );
DECLARE_DO_FUN( do_cmembers  );
DECLARE_DO_FUN( do_cnotes  );
DECLARE_DO_FUN( do_color  );
DECLARE_DO_FUN( do_commands );
DECLARE_DO_FUN( do_combine  );
DECLARE_DO_FUN( do_compact  );
DECLARE_DO_FUN( do_compare  );
DECLARE_DO_FUN( do_consider );
DECLARE_DO_FUN( do_copyspell );
DECLARE_DO_FUN( do_count  );
DECLARE_DO_FUN( do_create   );
DECLARE_DO_FUN( do_credits  );
DECLARE_DO_FUN( do_cstat   );
DECLARE_DO_FUN( do_ctalk   );
DECLARE_DO_FUN( do_dae_tok );
DECLARE_DO_FUN( do_deaf   );
DECLARE_DO_FUN( do_delet  );
DECLARE_DO_FUN( do_delete );
DECLARE_DO_FUN( do_deny   );
DECLARE_DO_FUN( do_deposit );
DECLARE_DO_FUN( do_description  );
DECLARE_DO_FUN( do_die   );
DECLARE_DO_FUN( do_dirt   );
DECLARE_DO_FUN( do_disarm );
DECLARE_DO_FUN( do_disconnect );
DECLARE_DO_FUN( do_dismount     );
DECLARE_DO_FUN( do_display );
DECLARE_DO_FUN( do_dispvnum );
DECLARE_DO_FUN( do_dns    );
DECLARE_DO_FUN( do_donate );
DECLARE_DO_FUN( do_doublexp);
DECLARE_DO_FUN( do_down   );
DECLARE_DO_FUN( do_drag  );
DECLARE_DO_FUN( do_drink  );
DECLARE_DO_FUN( do_drop   );
DECLARE_DO_FUN( do_dump   );
DECLARE_DO_FUN( do_dweeb  );
DECLARE_DO_FUN( do_east   );
DECLARE_DO_FUN( do_eat    );
DECLARE_DO_FUN( do_echo   );
#ifdef OLC_VERSION
DECLARE_DO_FUN( do_edit   );
DECLARE_DO_FUN( do_matlog);
#endif
DECLARE_DO_FUN( do_emote  );
DECLARE_DO_FUN( do_endgladiator );
DECLARE_DO_FUN( do_endow   );
DECLARE_DO_FUN( do_enemy   );
DECLARE_DO_FUN( do_enter  );
DECLARE_DO_FUN( do_envenom  );
DECLARE_DO_FUN( do_eqlist  );
DECLARE_DO_FUN( do_equipment  );
DECLARE_DO_FUN( do_establish );
DECLARE_DO_FUN( do_examine  );
DECLARE_DO_FUN( do_exits  );
DECLARE_DO_FUN( do_explode );
DECLARE_DO_FUN( do_fade         );
DECLARE_DO_FUN( do_fear  );
DECLARE_DO_FUN( do_fill   );
DECLARE_DO_FUN( do_flag   );
DECLARE_DO_FUN( do_flee   );
DECLARE_DO_FUN( do_focus   );
DECLARE_DO_FUN( do_follow );
DECLARE_DO_FUN( do_force  );
DECLARE_DO_FUN( do_forge  );
DECLARE_DO_FUN( do_freeze );
DECLARE_DO_FUN( do_fuck   );
DECLARE_DO_FUN( do_full_sac );
DECLARE_DO_FUN( do_gain   );
DECLARE_DO_FUN( do_garotte);
DECLARE_DO_FUN( do_get    );
DECLARE_DO_FUN( do_get_voucher );
DECLARE_DO_FUN( do_gladiator );
DECLARE_DO_FUN( do_gbet );
DECLARE_DO_FUN( do_glance );
DECLARE_DO_FUN( do_grab   );
DECLARE_DO_FUN( do_grenade );
DECLARE_DO_FUN( do_gscore );
DECLARE_DO_FUN( do_gtscore );
DECLARE_DO_FUN( do_gstatus );
DECLARE_DO_FUN( do_infuse );
DECLARE_DO_FUN( do_hex  );
DECLARE_DO_FUN( do_lag    );
DECLARE_DO_FUN( do_level    );
DECLARE_DO_FUN( do_lick );
DECLARE_DO_FUN( do_link );
DECLARE_DO_FUN( do_linksafe     );
DECLARE_DO_FUN( do_loot   );
DECLARE_DO_FUN( do_give   );
DECLARE_DO_FUN( do_bitch  );
DECLARE_DO_FUN( do_gossip );
DECLARE_DO_FUN( do_goto   );
DECLARE_DO_FUN( do_grats  );
DECLARE_DO_FUN( do_group  );
DECLARE_DO_FUN( do_gprompt );
DECLARE_DO_FUN( do_groups );
DECLARE_DO_FUN( do_gtell  );
DECLARE_DO_FUN( do_guild  );
DECLARE_DO_FUN( do_hd   );
DECLARE_DO_FUN( do_heal   );
DECLARE_DO_FUN( do_help   );
DECLARE_DO_FUN( do_hedit   );
DECLARE_DO_FUN( do_hide   );
DECLARE_DO_FUN( do_highlander );
DECLARE_DO_FUN( do_holylight  );
DECLARE_DO_FUN( do_hostmask  );
DECLARE_DO_FUN( do_idea   );
DECLARE_DO_FUN( do_ident );
DECLARE_DO_FUN( do_icg );
DECLARE_DO_FUN( do_ignore );
DECLARE_DO_FUN( do_immtalk  );
DECLARE_DO_FUN( do_incognito  );
DECLARE_DO_FUN( do_insanity  );
DECLARE_DO_FUN( do_clantalk );
DECLARE_DO_FUN( do_imotd  );
DECLARE_DO_FUN( do_imm_loads  );
DECLARE_DO_FUN( do_immnote   );
DECLARE_DO_FUN( do_inventory  );
DECLARE_DO_FUN( do_invis  );
DECLARE_DO_FUN( do_join  );
// Line below added 03SEP00 by Boogums
DECLARE_DO_FUN( do_kcharge );
DECLARE_DO_FUN( do_kick   );
DECLARE_DO_FUN( do_kill   );
DECLARE_DO_FUN( do_kit  );
DECLARE_DO_FUN( do_knock );
DECLARE_DO_FUN( do_kr   );
DECLARE_DO_FUN( do_list   );
DECLARE_DO_FUN( do_listen       );
DECLARE_DO_FUN( do_load   );
DECLARE_DO_FUN( do_lock   );
DECLARE_DO_FUN( do_log    );
DECLARE_DO_FUN( do_longeq );
DECLARE_DO_FUN( do_loner );
DECLARE_DO_FUN( do_look   );
DECLARE_DO_FUN( do_macro  );
DECLARE_DO_FUN( do_memory );
DECLARE_DO_FUN( do_mfind  );
DECLARE_DO_FUN( do_mload  );
DECLARE_DO_FUN( do_morph  );
DECLARE_DO_FUN( do_mount        );
DECLARE_DO_FUN( do_movehall     );
DECLARE_DO_FUN( do_mset   );
DECLARE_DO_FUN( do_mstat  );
DECLARE_DO_FUN( do_mwhere );
DECLARE_DO_FUN( do_motd   );
DECLARE_DO_FUN( do_murde  );
DECLARE_DO_FUN( do_murder );
DECLARE_DO_FUN( do_music  );
DECLARE_DO_FUN( do_name );
DECLARE_DO_FUN( do_newbie );
DECLARE_DO_FUN( do_newlock  );
DECLARE_DO_FUN( do_news   );
DECLARE_DO_FUN( do_nocancel  );
DECLARE_DO_FUN( do_nooutofrange  );
DECLARE_DO_FUN( do_no_dns );
DECLARE_DO_FUN( do_nogladiator );
DECLARE_DO_FUN( do_norecall );
DECLARE_DO_FUN( do_norescue );
DECLARE_DO_FUN( do_nochannels );
DECLARE_DO_FUN( do_noemote  );
DECLARE_DO_FUN( do_nofollow );
DECLARE_DO_FUN( do_noloot );
DECLARE_DO_FUN( do_nonotes );
DECLARE_DO_FUN( do_north  );
DECLARE_DO_FUN( do_noshout  );
DECLARE_DO_FUN( do_nosummon );
DECLARE_DO_FUN( do_note   );
DECLARE_DO_FUN( do_notel );
DECLARE_DO_FUN( do_notell );
DECLARE_DO_FUN( do_notitle );
DECLARE_DO_FUN( do_nowake );
DECLARE_DO_FUN( do_ofind  );
DECLARE_DO_FUN( do_offer  );
DECLARE_DO_FUN( do_oload  );
DECLARE_DO_FUN( do_onote  );
DECLARE_DO_FUN( do_ooc  );
DECLARE_DO_FUN( do_open   );
DECLARE_DO_FUN( do_order  );
DECLARE_DO_FUN( do_odds   );
DECLARE_DO_FUN( do_oset   );
DECLARE_DO_FUN( do_ostat  );
DECLARE_DO_FUN( do_outcas );
DECLARE_DO_FUN( do_outcast );
DECLARE_DO_FUN( do_outfit );
DECLARE_DO_FUN( do_owhere );
DECLARE_DO_FUN( do_olist );
DECLARE_DO_FUN( do_pardon );
DECLARE_DO_FUN( do_password );
DECLARE_DO_FUN( do_peace  );
DECLARE_DO_FUN( do_pecho  );
DECLARE_DO_FUN( do_pedit  );
DECLARE_DO_FUN( do_peek  );
DECLARE_DO_FUN( do_penalty  );
DECLARE_DO_FUN( do_pnet  );
DECLARE_DO_FUN( do_permban  );
DECLARE_DO_FUN( do_pick   );
DECLARE_DO_FUN( do_play   );
DECLARE_DO_FUN( do_pload );
DECLARE_DO_FUN( do_punload );
DECLARE_DO_FUN( do_pray   );
DECLARE_DO_FUN( do_pledg  );
DECLARE_DO_FUN( do_pledge   );
DECLARE_DO_FUN( do_pmote  );
DECLARE_DO_FUN( do_pose   );
DECLARE_DO_FUN( do_pour   );
DECLARE_DO_FUN( do_practice );
DECLARE_DO_FUN( do_prompt );
DECLARE_DO_FUN( do_protect  );
DECLARE_DO_FUN( do_pur    );
DECLARE_DO_FUN( do_purge  );
DECLARE_DO_FUN( do_put    );
DECLARE_DO_FUN( do_qnotes  );
DECLARE_DO_FUN( do_quaff  );
DECLARE_DO_FUN( do_question );
DECLARE_DO_FUN( do_qui    );
DECLARE_DO_FUN( do_quiet  );
DECLARE_DO_FUN( do_quit   );
DECLARE_DO_FUN( do_quit_command   );
DECLARE_DO_FUN( do_quicken   );
DECLARE_DO_FUN( do_quest  );
DECLARE_DO_FUN( do_rage         );
DECLARE_DO_FUN( do_rank   );
DECLARE_DO_FUN( do_read   );
DECLARE_DO_FUN( do_reboo  );
DECLARE_DO_FUN( do_reboot );
DECLARE_DO_FUN( do_recall );
DECLARE_DO_FUN( do_recho  );
DECLARE_DO_FUN( do_recite );
DECLARE_DO_FUN( do_reclas );
DECLARE_DO_FUN( do_reclass);
#ifdef ANDARONDEV
DECLARE_DO_FUN( do_reloadme   );
#endif
DECLARE_DO_FUN( do_remort );
DECLARE_DO_FUN( do_remove );
DECLARE_DO_FUN( do_removegladiator );
DECLARE_DO_FUN( do_rename );
DECLARE_DO_FUN( do_rent   );
DECLARE_DO_FUN( do_replay );
DECLARE_DO_FUN( do_reply  );
DECLARE_DO_FUN( do_review  );
DECLARE_DO_FUN( do_rlock  );
DECLARE_DO_FUN( do_noreply  );
DECLARE_DO_FUN( do_repair );
DECLARE_DO_FUN( do_report );
DECLARE_DO_FUN( do_rescue );
DECLARE_DO_FUN( do_rest   );
DECLARE_DO_FUN( do_restore  );
DECLARE_DO_FUN( do_return );
DECLARE_DO_FUN( do_reward );
DECLARE_DO_FUN( do_ritual       );
DECLARE_DO_FUN( do_roar   );
DECLARE_DO_FUN( do_rset   );
DECLARE_DO_FUN( do_rstat  );
DECLARE_DO_FUN( do_rules  );
DECLARE_DO_FUN( do_sacrifice  );
DECLARE_DO_FUN( do_sanction );
DECLARE_DO_FUN( do_save   );
DECLARE_DO_FUN( do_whisper );
DECLARE_DO_FUN( do_sayto  );
DECLARE_DO_FUN( do_say    );
DECLARE_DO_FUN( do_score  );
DECLARE_DO_FUN( do_cscore  );
DECLARE_DO_FUN( do_scribe );
DECLARE_DO_FUN( do_scroll );
DECLARE_DO_FUN( do_search );
DECLARE_DO_FUN( do_sell   );
DECLARE_DO_FUN( do_set    );
DECLARE_DO_FUN( do_setcouncil);
DECLARE_DO_FUN( do_shapemorph );
DECLARE_DO_FUN( do_shapeshift );
DECLARE_DO_FUN( do_sharpen );
DECLARE_DO_FUN( do_shout  );
DECLARE_DO_FUN( do_show   );
DECLARE_DO_FUN( do_shutdow  );
DECLARE_DO_FUN( do_shutdown );
DECLARE_DO_FUN( do_silence  );
DECLARE_DO_FUN( do_sit    );
DECLARE_DO_FUN( do_skills );
DECLARE_DO_FUN( do_skipbet );
DECLARE_DO_FUN( do_skstat );
DECLARE_DO_FUN( do_sla    );
DECLARE_DO_FUN( do_slay   );
DECLARE_DO_FUN( do_sleep  );
DECLARE_DO_FUN( do_slice        );
DECLARE_DO_FUN( do_slookup  );
DECLARE_DO_FUN( do_smote  );
DECLARE_DO_FUN( do_snatch );
DECLARE_DO_FUN( do_sneak  );
DECLARE_DO_FUN( do_snoop  );
DECLARE_DO_FUN( do_socials  );
DECLARE_DO_FUN( do_south  );
// DECLARE_DO_FUN( do_socke  );
DECLARE_DO_FUN( do_sockets  );
DECLARE_DO_FUN( do_specializ );
DECLARE_DO_FUN( do_specialize );
DECLARE_DO_FUN( do_species      );
DECLARE_DO_FUN( do_spells );
DECLARE_DO_FUN( do_split  );
DECLARE_DO_FUN( do_spool  );
DECLARE_DO_FUN( do_spreward );
DECLARE_DO_FUN( do_spy );
DECLARE_DO_FUN( do_sset   );
DECLARE_DO_FUN( do_stand  );
DECLARE_DO_FUN( do_startgladiator );
DECLARE_DO_FUN( do_stat   );
DECLARE_DO_FUN( do_steal  );
DECLARE_DO_FUN( do_story  );
DECLARE_DO_FUN( do_string );
DECLARE_DO_FUN( do_surname      );
DECLARE_DO_FUN( do_switch );
DECLARE_DO_FUN( do_syncarea );
DECLARE_DO_FUN( do_synchelps );
DECLARE_DO_FUN( do_tail_slap );
DECLARE_DO_FUN( do_tell   );
DECLARE_DO_FUN( do_text   );
DECLARE_DO_FUN( do_throw   );
DECLARE_DO_FUN( do_time   );
DECLARE_DO_FUN( do_timestamps   );
DECLARE_DO_FUN( do_title  );
DECLARE_DO_FUN( do_trade        );
DECLARE_DO_FUN( do_train  );
DECLARE_DO_FUN( do_transfer );
DECLARE_DO_FUN( do_trip   );
DECLARE_DO_FUN( do_trap   );
DECLARE_DO_FUN( do_trust  );
DECLARE_DO_FUN( do_typo   );
DECLARE_DO_FUN( do_unalias  );
DECLARE_DO_FUN( do_undns  );
DECLARE_DO_FUN( do_unlock );
DECLARE_DO_FUN( do_unlink  );
DECLARE_DO_FUN( do_unmacro);
DECLARE_DO_FUN( do_unread );
DECLARE_DO_FUN( do_up   );
DECLARE_DO_FUN( do_value  );
DECLARE_DO_FUN( do_visible  );
DECLARE_DO_FUN( do_violate  );
DECLARE_DO_FUN( do_vnum   );
DECLARE_DO_FUN( do_wake   );
DECLARE_DO_FUN( do_wear   );
DECLARE_DO_FUN( do_weather  );
DECLARE_DO_FUN( do_west   );
DECLARE_DO_FUN( do_where  );
DECLARE_DO_FUN( do_who    );
DECLARE_DO_FUN( do_whois  );
DECLARE_DO_FUN( do_wimpy  );
DECLARE_DO_FUN( do_withdraw );
DECLARE_DO_FUN( do_wizhelp  );
DECLARE_DO_FUN( do_wizlock  );
DECLARE_DO_FUN( do_wizlist  );
DECLARE_DO_FUN( do_wiznet );
DECLARE_DO_FUN( do_wraithform_return );
DECLARE_DO_FUN( do_worth  );
DECLARE_DO_FUN( do_yell   );
DECLARE_DO_FUN( do_zap    );
DECLARE_DO_FUN( do_zecho  );
DECLARE_DO_FUN( do_hamstring );
DECLARE_DO_FUN( action_wraithform );
DECLARE_DO_FUN( action_ambush );
DECLARE_DO_FUN( do_shieldbash );
DECLARE_DO_FUN( do_bounty );
DECLARE_DO_FUN( do_ftick);
/* */
